package com.ptm.personaltaskmanager.database;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;

import com.ptm.personaltaskmanager.model.Tasks;
import com.ptm.personaltaskmanager.model.Users;

public interface CreateTaskRespository extends JpaRepository<Tasks, Integer>{
	  /*
     * No custom methods are needed here because:
     *
     * 1. JpaRepository already provides all CRUD operations, including save().
     *    - Calling save() with a new entity (null ID) always performs an INSERT.
     *
     * 2. We do not enforce uniqueness or check for duplicates.
     *    - Since duplicates are allowed, we do NOT need findByTitle(), existsByX(), or any lookup.
     *
     * 3. The ID is auto-generated by the database.
     *    - Because the @Id field is generated, each save() call produces a new row automatically.
     *
     * 4. No custom queries are required.
     *    - We are not filtering, searching, or validating anything before insert.
     *
     * This keeps the repository clean, minimal, and aligned with Spring Data best practices.
     */
}
