spring:
  profiles:
    active: dev   # default profile

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

weather:
  api:
    timeout-ms: 5000   # shared default timeout for all environments

logging:
 file:
  name: logs/apps.log
 level:
  root: DEBUG